include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'
  
variables:
  MODERNGL_DEBUGGING: "true"
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
  CI_DEV_PKGS: "Makie#master AbstractPlotting#master GLMakie#master MakieLayout#master Proj4#master"


test:1.3:
  tags:
    - xorg
  extends:
    - .julia:1.3
  script:
    - julia -e 'using Pkg; pkg"add $CI_DEV_PKGS"'
    - julia --project -e 'using Pkg;
                      Pkg.instantiate();
                      Pkg.build();
                      Pkg.test(; coverage=true);'
                      
